/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.io.IOException;

import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;

import model.FundInfoManager;

/**
 *
 * @author bondwong
 */
public class DataPane extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5527841366827215321L;
	/**
     * Creates new form HomePane
	 * @throws IOException 
     */
    public DataPane(FundInfoManager fim) throws IOException {
        this.fim = fim;
    	initComponents(fim.getRawBasicInfos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String[][] data) {

        queryButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fundBasicInfoTable = new javax.swing.JTable();

        queryButton.setText("查询");
        queryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					queryButtonMouseClicked(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        
        fundBasicInfoTable.setModel(new FundDataTableModel(
        	data,
            new String [] {
        		"基金代号","基金简称","基金全称","基金类型"
            }
        ));
        fundBasicInfoTable.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        fundBasicInfoTable.setSize(new java.awt.Dimension(400, 350));
        fundBasicInfoTable.getColumnModel().setColumnSelectionAllowed(false);
        for(int i=0;i<fundBasicInfoTable.getColumnCount();i++){
        	fundBasicInfoTable.getColumnModel().getColumn(i).setResizable(false);
        }
        
        fundBasicInfoTable.getTableHeader().setReorderingAllowed(false);
        
        jScrollPane2.setViewportView(fundBasicInfoTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(queryButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void queryButtonMouseClicked(java.awt.event.MouseEvent evt) throws IOException {                                         
        // TODO add your handling code here:
        int[] rowIndexs = fundBasicInfoTable.getSelectedRows();
        System.out.println(rowIndexs.length);
        if(rowIndexs.length != 0){
        	TableModel model = fundBasicInfoTable.getModel();
        	String[] fundCodes = new String[rowIndexs.length];
        	
        	for(int i=0 ;i<rowIndexs.length ;i++){
        		fundCodes[i] = (String) model.getValueAt(rowIndexs[i], 0);
        	}
        	JPanel panel = LineChart.createLineChart(fim, fundCodes);
        	LineChartDialog dialog = new LineChartDialog(panel, new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        	System.out.println(fundCodes.length);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fundBasicInfoTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton queryButton;
    // End of variables declaration//GEN-END:variables
    
	private FundInfoManager fim;
}
