/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import gui.MainFrame;

import java.io.IOException;

import javax.swing.JFrame;

import model.FundInfoManager;

/**
 *
 * @author bondwong
 */
public class MainFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4756550894833972279L;

	/**
     * Creates new form MainFrame
     * @throws IOException 
     */
    public MainFrame() throws IOException {
    	initData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initData() throws IOException {
    	fim = FundInfoManager.getInstance();
    	fim.init();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws IOException {

        jTabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        dataPane1 = new DataPane(fim);
        namedQueryPane = new javax.swing.JPanel();
        namedQueryPane1 = new NamedQueryPane(fim);
        rangeQueryPane = new javax.swing.JPanel();
        rangePane2 = new RangePane(fim);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        dataPane1.setPreferredSize(new java.awt.Dimension(400, 350));

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dataPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(dataPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane.addTab("主页", homePanel);

        namedQueryPane1.setMinimumSize(new java.awt.Dimension(400, 195));

        javax.swing.GroupLayout namedQueryPaneLayout = new javax.swing.GroupLayout(namedQueryPane);
        namedQueryPane.setLayout(namedQueryPaneLayout);
        namedQueryPaneLayout.setHorizontalGroup(
            namedQueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namedQueryPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(namedQueryPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        namedQueryPaneLayout.setVerticalGroup(
            namedQueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namedQueryPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(namedQueryPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("按名查询", namedQueryPane);

        javax.swing.GroupLayout rangeQueryPaneLayout = new javax.swing.GroupLayout(rangeQueryPane);
        rangeQueryPane.setLayout(rangeQueryPaneLayout);
        rangeQueryPaneLayout.setHorizontalGroup(
            rangeQueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rangeQueryPaneLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(rangePane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        rangeQueryPaneLayout.setVerticalGroup(
            rangeQueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rangeQueryPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(rangePane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("范围查询", rangeQueryPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws IOException 
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        	JFrame frame = new MainFrame();

			@Override
			public void run() {
				// TODO Auto-generated method stub
				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame.setTitle("FundHelper");
	        	frame.setVisible(true);
	            frame.setVisible(true);
			}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.DataPane dataPane1;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel namedQueryPane;
    private gui.NamedQueryPane namedQueryPane1;
    private gui.RangePane rangePane2;
    private javax.swing.JPanel rangeQueryPane;
    // End of variables declaration//GEN-END:variables
    
    private FundInfoManager fim;
}
