/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.io.IOException;

import javax.swing.table.TableModel;

import model.Fund;
import model.FundInfoManager;

/**
 *
 * @author bondwong
 */
public class MultiRowsDataPane extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8154712924411008333L;
	/**
     * Creates new form MultiRowsDataPane
     */
    public MultiRowsDataPane(FundInfoManager fim) {
    	this.fim = fim;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fundBasicInfoTable = new javax.swing.JTable();

        queryButton.setText("查询");
        queryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					queryButtonMouseClicked(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        fundBasicInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "基金代码", "基金简称", "基金全称", "基金类型"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fundBasicInfoTable);
        if (fundBasicInfoTable.getColumnModel().getColumnCount() > 0) {
            fundBasicInfoTable.getColumnModel().getColumn(0).setResizable(false);
            fundBasicInfoTable.getColumnModel().getColumn(1).setResizable(false);
            fundBasicInfoTable.getColumnModel().getColumn(2).setResizable(false);
            fundBasicInfoTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(queryButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void queryButtonMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_queryButtonMouseClicked
        // TODO add your handling code here:
        int rowIndex = fundBasicInfoTable.getSelectedRow();
        if(rowIndex != -1){
            TableModel model = fundBasicInfoTable.getModel();
            String fundCode = (String) model.getValueAt(rowIndex, 0);
            String fundName = (String) model.getValueAt(rowIndex, 2);
            Fund fund = new Fund(fundName);
            fund.setTimeMap(fim.getRecords(fundCode));
            System.out.println(fundCode);
        }
    }//GEN-LAST:event_queryButtonMouseClicked
    
    @SuppressWarnings("serial")
	public void setData(Object[][] datas){
    	this.fundBasicInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            datas,
            new String [] {
                "基金代码", "基金简称", "基金全称", "基金类型"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @SuppressWarnings({ "rawtypes", "unchecked" })
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fundBasicInfoTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton queryButton;
    // End of variables declaration//GEN-END:variables
    
    private FundInfoManager fim;
}
