/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.io.IOException;
import java.util.List;

import model.FundInfoManager;

/**
 *
 * @author bondwong
 */
public class NamedQueryPane extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6566771399332267479L;
	/**
     * Creates new form NamedQueryPane
     */
    public NamedQueryPane(FundInfoManager fim) {
    	this.fim = fim;
        initComponents(fim.getFundCodes().toArray(), fim.getFundSNs().toArray(), fim.getFundNames().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Object[] fundCodes, Object[] fundSNs, Object[] fundNames) {

        fundCodeLabel = new javax.swing.JLabel();
        fundSNLabel = new javax.swing.JLabel();
        fundNameLabel = new javax.swing.JLabel();
        queryButton = new javax.swing.JButton();
        fundCodeComboBox = new javax.swing.JComboBox();
        fundSNComboBox = new javax.swing.JComboBox();
        fundNameComboBox = new javax.swing.JComboBox();
        singleRowDataPane1 = new SingleRowDataPane(this.fim);
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(400, 195));
        
        singleRowDataPane1.setVisible(false);
        
        fundCodeLabel.setText("基金代码:");

        fundSNLabel.setText("基金简称:");

        fundNameLabel.setText("基金全名:");

        queryButton.setText("查询");
        queryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					queryButtonMouseClicked(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        fundCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(fundCodes));
        fundCodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundCodeComboBoxActionPerformed(evt);
            }
        });
        
        fundSNComboBox.setModel(new javax.swing.DefaultComboBoxModel(fundSNs));
        fundSNComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundSNComboBoxActionPerformed(evt);
            }
        });

        fundNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(fundNames));
        fundNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundNameComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(singleRowDataPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fundCodeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fundCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fundSNLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fundSNComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fundNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fundNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fundCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fundSNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundSNComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fundNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fundNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(queryButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(singleRowDataPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents// </editor-fold>//GEN-END:initComponents

    private void queryButtonMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_queryButtonMouseClicked
        // TODO add your handling code here:
        String fundCode = (String) fundCodeComboBox.getSelectedItem();
        List<String> basicInfo = fim.getBasicInfo(fundCode);
        Object[][] data = new Object[][]{basicInfo.toArray()};
        singleRowDataPane1.setData(data);
        singleRowDataPane1.setVisible(true);
        System.out.println(basicInfo);
    }//GEN-LAST:event_queryButtonMouseClicked

    private void fundSNComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundSNComboBoxActionPerformed
        // TODO add your handling code here:
    	String fundName = (String) fundSNComboBox.getSelectedItem();
    	String[] basicInfo = fim.getBasicInfoBySN(fundName);
    	fundCodeComboBox.setSelectedItem(basicInfo[0]);
    	fundNameComboBox.setSelectedItem(basicInfo[2]);
    }//GEN-LAST:event_fundSNComboBoxActionPerformed

    private void fundNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundNameComboBoxActionPerformed
        // TODO add your handling code here:
    	String fundName = (String) fundNameComboBox.getSelectedItem();
    	String[] basicInfo = fim.getBasicInfoByName(fundName);
    	fundCodeComboBox.setSelectedItem(basicInfo[0]);
    	fundSNComboBox.setSelectedItem(basicInfo[1]);
    }//GEN-LAST:event_fundNameComboBoxActionPerformed
    
    private void fundCodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
    	String fundName = (String) fundCodeComboBox.getSelectedItem();
    	List<String> basicInfo = fim.getBasicInfo(fundName);
    	fundNameComboBox.setSelectedItem(basicInfo.get(2));
    	fundSNComboBox.setSelectedItem(basicInfo.get(1));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox fundCodeComboBox;
    private javax.swing.JLabel fundCodeLabel;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox fundNameComboBox;
    private javax.swing.JLabel fundNameLabel;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox fundSNComboBox;
    private javax.swing.JLabel fundSNLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton queryButton;
    private SingleRowDataPane singleRowDataPane1;
    // End of variables declaration//GEN-END:variables
    
	private FundInfoManager fim;
}
