/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.io.IOException;

import javax.swing.table.TableModel;

import model.Fund;
import model.FundInfoManager;

/**
 *
 * @author bondwong
 */
public class SingleRowDataPane extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2814177054234939989L;
	/**
     * Creates new form SingleRowDataPane
     */
    public SingleRowDataPane(FundInfoManager fim) {
    	this.fim = fim;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fundBasicTable = new javax.swing.JTable();
        queryButton = new javax.swing.JButton();

        fundBasicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "基金代码", "基金简称", "基金全称", "基金类型"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fundBasicTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fundBasicTable.setShowGrid(false);
        fundBasicTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(fundBasicTable);
        jScrollPane1.setSize(400, 40);
        if (fundBasicTable.getColumnModel().getColumnCount() > 0) {
            fundBasicTable.getColumnModel().getColumn(0).setResizable(false);
            fundBasicTable.getColumnModel().getColumn(1).setResizable(false);
            fundBasicTable.getColumnModel().getColumn(2).setResizable(false);
            fundBasicTable.getColumnModel().getColumn(3).setResizable(false);
        }

        queryButton.setText("查询");
        queryButton.setSize(new java.awt.Dimension(96, 29));
        queryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					queryButtonMouseClicked(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(queryButton)
                .addGap(0, 58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void queryButtonMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_queryButtonMouseClicked
        // TODO add your handling code here:
        TableModel model = fundBasicTable.getModel();
        String fundCode = (String) model.getValueAt(0, 0);
        String fundName = (String) model.getValueAt(0, 2);
        Fund fund = new Fund(fundName);
        fund.setTimeMap(fim.getRecords(fundCode));
        System.out.println(fundCode);
    }//GEN-LAST:event_queryButtonMouseClicked
    
    @SuppressWarnings("serial")
	public void setData(Object[][] data) {
    	fundBasicTable.setModel(new javax.swing.table.DefaultTableModel(data, 
    			new String [] { "基金代码", "基金简称", "基金全称", "基金类型" } ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @SuppressWarnings({ "rawtypes", "unchecked" })
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fundBasicTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton queryButton;
    // End of variables declaration//GEN-END:variables
    
    private FundInfoManager fim;
}
